# Sunsetr configuration
sunset = "19:00:00"   # Time to transition to night mode (HH:MM:SS)
sunrise = "07:30:00"  # Time to transition to day mode (HH:MM:SS)
temp = 4000           # Color temperature after sunset (1000-6500) Kelvin
